version: "3.1"

services:
  example:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: example
    restart: unless-stopped
    depends_on:
      - db
      - adminer
    ports:
      - "4000:4000"
    environment:
      DOOBIE_URL: "jdbc:postgresql://db:5432/pgdb"

  db:
    image: postgres:9.6.8
    container_name: db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb
    volumes:
      - ./modules/example/src/main/resources/sql:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
