version: '3.1'

services:

  db:
    image: postgres:9.6.8
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
