object Versions {
  // compiler
  val kindProjectorVersion = "0.11.0"
  // project
  val collectionCompatVersion       = "2.1.4"
  val doobieVersion                 = "0.9.0"
  val shapelessVersion              = "2.3.3"
  val catsVersion                   = "2.1.1"
  val catsEffectVersion             = "2.1.3"
  val fs2Version                    = "2.3.0"
  val circeVersion                  = "0.13.0"
  val circeOpticsVersion            = "0.13.0"
  val sangriaVersion                = "1.4.2"
  val sangriaCirceVersion           = "1.3.0"
  val sangriaSlowLogVersion         = "0.1.8"
  val configVersion                 = "1.4.0"
  val akkaVersion                   = "2.6.5"
  val akkaHttpVersion               = "10.1.11"
  val akkaHttpCirceVersion          = "1.32.0"
  val slf4jVersion                  = "1.7.30"
  val log4jVersion                  = "2.13.2"
  val log4jScalaVersion             = "11.0"
  val jacksonVersion                = "2.11.0"
  val scalatestVersion              = "3.1.1"
  val testcontainersPostgresVersion = "1.14.1"
  val testcontainersScalaVersion    = "0.36.1"
}
