object Versions {
  // compiler
  val kindProjectorVersion = "0.10.3"
  // project
  val configVersion                 = "1.4.0"
  val shapelessVersion              = "2.3.3"
  val catsVersion                   = "2.0.0"
  val catsEffectVersion             = "2.0.0"
  val fs2Version                    = "2.1.0"
  val doobieVersion                 = "0.8.8"
  val circeVersion                  = "0.13.0"
  val circeOpticsVersion            = "0.13.0"
  val sangriaCirceVersion           = "1.3.0"
  val sangriaVersion                = "1.4.2"
  val scalatestVersion              = "3.1.1"
  val testcontainersPostgresVersion = "1.13.0"
  val testcontainersScalaVersion    = "0.36.0"
  val slf4jVersion                  = "1.7.30"
  val akkaVersion                   = "2.6.4"
  val akkaHttpVersion               = "10.1.11"
  val akkaHttpCirceVersion          = "1.31.0"
  val jacksonVersion                = "2.10.3"
  val log4jVersion                  = "2.13.1"
  val log4jScalaVersion             = "11.0"
}
